name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Replace .npmrc with the CI-ready version
        run: rm .npmrc && mv .npmrc.ci .npmrc
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@kwizapp'
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run lint:ci
      - run: npm run format:ci
      - run: npm run type-check

  build_docker_hub:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        if: github.branch == 'dev' || github.branch == 'master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image (prod)
        run: docker build -f Dockerfile.prod . --tag kwizapp/ionic-app:latest --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Docker Hub
        if: github.branch == 'dev' || github.branch == 'master'
        run: docker push kwizapp/ionic-app

  build_heroku:
    runs-on: ubuntu-latest
    needs: check
    if: github.branch == 'dev' || github.branch == 'master'

    steps:
      - uses: actions/checkout@v2
      - name: Pull the latest image from Docker Hub
        run: docker pull kwizapp/ionic-app:latest
      - uses: azure/docker-login@v1
        with:
          login-server: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build the Docker image
        run: docker build -f Dockerfile.prod . --cache-from kwizapp/ionic-app:latest --tag registry.heroku.com/kwiz-ionic-app/web --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Heroku
        run: docker push registry.heroku.com/kwiz-ionic-app/web

  deploy:
    runs-on: ubuntu-latest
    needs: [check, build_heroku]
    if: github.branch == 'dev' || github.branch == 'master'

    steps:
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Release the new version
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a kwiz-ionic-app web
